### ISSUE TITLE
Add transaction detail page

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-app#11]
Currently, the transactions page only has a truncated txid and an amount. It should allow the user to drill down and get the transaction details such as to, from, blockheight, number of confirmations, segwit/non-segwit, whether the transaction was part of a channel funding/closing etc.

**Comment by DaReaper** [comment]
Also add amount, fees, confirmations and timestamp to the transaction detail. Probably provide the ability to open and view additional information on a block / transaction explorer.

**Comment by fresheneesz** [comment]
The main line of the transaction history should also show the address its sending to rather than the txid, That's more important to people. 

Aggregating and embellishing the above:

* To 
* From
* blockheight
* Confirmations
* Date broadcast
* Date confirmed
* segwit/non-segwit (why would it be non-segwit?)
* what channel funding the transaction was for (if it was part of one)
* fee (or fees in the case of a LN transaction)
* additional info on a blockchain explorer

My own additions:

* What channel(s) the transaction was sent through (for a LN transaction)
* Whether the transaction failed or succeeded (with option to resend) and why it failed if it failed.

**Comment by fresheneesz** [comment]
@tanx Could you please comment on why you closed this?
