### ISSUE TITLE
Make wallet funding way more obvious

### ISSUE THREAD

**Issue by skwp** [lightninglabs/lightning-app#132]
### Description

The current way to fund the wallet is hidden under a completely non obvious feature (Request), where I'm not requesting money but rather want to send to the wallet's address. Secondly it's at the bottom of that area. It took me a full 5 minutes to find it.

The wallet needs to have a much better onboarding experience but in lieu of that we could at least add a tab that is called Fund Your Wallet that has the address and a small section of instructions.

<img width="833" alt="lightning_and_faucet_-_bitcoin_testnet_sandbox" src="https://user-images.githubusercontent.com/1731/34841941-8a7eda9e-f6cf-11e7-9933-967f9a599071.png">

**Comment by skwp** [comment]
Happy to try to implement this if there is consensus on this being a good idea. Thanks.

**Comment by r0zar** [comment]
(Possible idea)
Have a home screen interface that if no funds/channels are detected, starts a guided tour to load funds.

**Comment by bryanvu** [comment]
@skwp and @r0zar  I think it's definitely a good idea and we definitely need to do some work on the onboarding process. If you have ideas you're considering implementing, definitely feel free to post here or ping me in the Slack.

**Comment by MidnightLightning** [comment]
I agree having a separate menu item for "get funds into your account" makes sense instead of grouping it with "Request". As to what to name it, "Fund your wallet" makes sense to me, as long as there's consistent naming to separate "Wallet" and "Channels" throughout the app. Another option I'd suggest is "Deposit"; most exchange sites use "Deposit/withdraw" as the verbs for getting funds into and out of the wallet you're looking at, to differentiate it from "Trade" which keeps your funds within the system.

**Comment by machine-uprising** [comment]
Had the same problem trying to find out how to fund wallet. I like the idea from @MidnightLightning for  "Fund your wallet".
The idea from @r0zar I think is good as well. Nice to have some information available when first running the application. Including information in the application or a link to a setup/funding document would be a help.
