### ISSUE TITLE
open ../lnd.conf: The system cannot find the file specified

### ISSUE THREAD

**Issue by vitorbgs** [lightninglabs/lightning-app#203]
Using windows GUI version

The first line of the log is always saying the system cannot find lnd.conf 

I tried putting it on \AppData\Local\Lnd and on the executable folder

### Expected behavior
To find lnd.conf

**Comment by vwoo** [comment]
I have the same problem in the macOS packaged v0.1.5-alpha release.

I tried creating /Users/[username]/Library/Application Support/Lnd/lnd.conf but the log says:
2018-02-17 01:20:08.937 [WRN] LTND: open ../lnd.conf: no such file or directory

The lightning-app README.md suggests we need to run in development mode for reading lnd.conf but it doesn't explicitly say the packaged release doesn't. But it would be handy because I would like to tell the lightning-app to connect to my local bitcoind test node via lnd.conf.

**Comment by Roasbeef** [comment]
This isn't actually an issue as within the application, we _purposefully_ point it towards a non-existent `lnd.conf`. This allows us to ensure that the application is launched with the proper set of arguments.
