### ISSUE TITLE
App is stuck in wallet initialization stage

### ISSUE THREAD

**Issue by mntetai** [lightninglabs/lightning-app#206]
### Description
When app is started , wallet fails to open.
### Steps to reproduce the behavior
Install version 0.1.5 on win10 pro , sync all headers , restart application.
### Expected behavior
Application should show public address.
### Actual behavior
Application is stuck in wallet initialization stage , public address is not shown ..

### Screenshot and/or logs if applicable
<pre>
Logs
lnd: 2018-02-08 18:19:43.970 [INF] LNWL: Done catching up block hashes 2018-02-08 18:19:43.970 [INF] LNWL: Finished rescan for 1 address (synced to block 0000000000002cb4ff533b832cbdf1962c732c33ebc9d69ec14f96fb1f984b66, height 1280241)
lnd: 2018-02-08 18:19:44.598 [INF] LTND: Chain backend is fully synced (end_height=1280241)! 2018-02-08 18:19:44.598 [INF] HSWC: Starting HTLC Switch
lnd: 2018-02-08 18:19:44.598 [INF] NTFN: New block epoch subscription 2018-02-08 18:19:44.598 [INF] UTXN: Processing outputs from missed blocks. Starting with blockHeight=1280235, to current blockHeight=1280241
lnd: 2018-02-08 18:19:44.598 [INF] UTXN: Attempting to graduate height=1280236: num_kids=0, num_babies=0
lnd: 2018-02-08 18:19:44.729 [INF] UTXN: Attempting to graduate height=1280237: num_kids=0, num_babies=0
lnd: 2018-02-08 18:19:44.829 [INF] UTXN: Attempting to graduate height=1280238: num_kids=0, num_babies=0
lnd: 2018-02-08 18:19:44.929 [INF] UTXN: Attempting to graduate height=1280239: num_kids=0, num_babies=0
lnd: 2018-02-08 18:19:45.028 [INF] UTXN: Attempting to graduate height=1280240: num_kids=0, num_babies=0
lnd: 2018-02-08 18:19:45.195 [INF] UTXN: Attempting to graduate height=1280241: num_kids=0, num_babies=0
lnd: 2018-02-08 18:19:45.295 [INF] UTXN: UTXO Nursery is now fully synced 2018-02-08 18:19:45.295 [INF] DISC: Authenticated Gossiper is starting
lnd: 2018-02-08 18:19:45.295 [INF] BRAR: Starting contract observer with 0 active channels 2018-02-08 18:19:45.296 [INF] CRTR: FilteredChainView starting 2018-02-08 18:19:45.296 [INF] CRTR: Filtering chain using 0 channels active
lnd: 2018-02-08 18:19:45.296 [INF] CRTR: Prune tip for Channel Graph: height=1280235, hash=00000000000023c8e40c008189975c8136e3d882c9f80f93a585f0cf7c0e8b24
lnd: 2018-02-08 18:19:45.296 [INF] CRTR: Syncing channel graph from height=1280235 (hash=00000000000023c8e40c008189975c8136e3d882c9f80f93a585f0cf7c0e8b24) to height=1280241 (hash=0000000000002cb4ff533b832cbdf1962c732c33ebc9d69ec14f96fb1f984b66)
lnd: 2018-02-08 18:19:45.296 [INF] NTFN: New block epoch subscription
lnd: 2018-02-08 18:19:45.344 [INF] CRTR: Block 0000000000000c395849912de24750f5261b5c661397ae274d5c9bb956eb756c (height=1280236) closed 0 channels
lnd: 2018-02-08 18:19:45.427 [INF] CRTR: Block 00000000000027d08cf44d3641e74632184a5878fd934f76f8e0ea2da6073a79 (height=1280237) closed 0 channels
lnd: 2018-02-08 18:19:45.478 [INF] CRTR: Block 00000000000024373e8048dc348e1cffa3699efaadbbbb25611d907cada60f0f (height=1280238) closed 0 channels
lnd: 2018-02-08 18:19:45.536 [INF] CRTR: Block 00000000000006d40d85a20c00700243cd677557e6b0b03db64f798b319d42b4 (height=1280239) closed 0 channels
lnd: 2018-02-08 18:19:45.586 [INF] CRTR: Block 0000000000002343018f7ab248272e5f99ef78ad3ff42946f214e55bff752ab1 (height=1280240) closed 0 channels
lnd: 2018-02-08 18:19:45.645 [INF] CRTR: Block 0000000000002cb4ff533b832cbdf1962c732c33ebc9d69ec14f96fb1f984b66 (height=1280241) closed 0 channels 2018-02-08 18:19:45.645 [INF] CRTR: Graph pruning complete: 0 channels were closed since height 1280235
lnd: 2018-02-08 18:19:45.645 [INF] SRVR: Initializing peer network bootstrappers! 2018-02-08 18:19:45.645 [INF] SRVR: Creating DNS peer bootstrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory]]
lnd: 2018-02-08 18:19:45.645 [INF] ATPL: Instantiating autopilot with cfg: (*main.autoPilotConfig)(0xc0424ecda0)({ Active: (bool) true, MaxChannels: (int) 5, Allocation: (float64) 0.6 })
lnd: 2018-02-08 18:19:45.645 [INF] ATPL: Autopilot Agent starting
lnd: 2018-02-08 18:19:45.645 [INF] CMGR: Server listening on [::]:9735 2018-02-08 18:19:45.645 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2018-02-08 18:19:45.646 [INF] ATPL: Processing new external signal
lnd: 2018-02-08 18:19:45.646 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]
lnd: 2018-02-08 18:19:56.763 [INF] DISC: Obtained 3 addrs to bootstrap network with
lnd: 2018-02-08 18:19:57.100 [ERR] SRVR: unable to connect to 02cac4044ec19e24489532b106013cc0d3e121a0a74d6d70748bcae8fa53ea213d@158.69.180.187:9735: EOF
lnd: 2018-02-08 18:19:57.178 [INF] SRVR: Established connection to: 109.99.154.45:9735
lnd: 2018-02-08 18:19:57.310 [INF] DISC: Syncing channel graph state with 02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855, sending 0 vertexes and 0 edges 2018-02-08 18:19:57.310 [INF] SRVR: Attempting to send msgs 0 to: 02575c8b82dcb4b2936ef52326fa952127f9e85748b50abec4111bbd35e834b855
lnd: 2018-02-08 18:19:57.606 [ERR] SRVR: unable to connect to 03f3ae3c64338b0545ba12493421c6782aae7e43be7332f5658a5ae29cea0119da@172.104.59.47:9735: EOF
lnd: 2018-02-08 18:20:05.791 [INF] CRTR: New channel discovered! Link connects 024c873f489141f6581c78a8af32a6209eb23847ca55c18b4032e6789af1abfcd0 and 0392419c02fbca83ae8d541cd2f48b662b2238ed8e1e92a93547c23ba32f0d64c6 with ChannelPoint(d7e4199f49548a7d71b90345efe839c2c75e2fad0149bd905509a3be82997e31:1): chan_id=1406899894530146305, capacity=0.005 BTC
lnd: 2018-02-08 18:20:06.289 [INF] CRTR: New channel discovered! Link connects 03324ef21e77714cdc1ad7fadda808a7aca2b7f8d31cd737923d42164dac00a02d and 03e372c5b94d893bd297bd559dea33733add424462ffae7e3cf5350b8b0cc5cd45 with ChannelPoint(1674621aaf884831ae89b89d94e91bc8498279117e27b0145565944dc8b871b8:0): chan_id=1406844918948823040, capacity=0.1 BTC
lnd: 2018-02-08 18:20:07.136 [INF] CRTR: New channel discovered! Link connects 0343149dd5bec6cbdfb4eb4913c71b9d710edf30207382f3a5755c252d2997c99d and 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 with ChannelPoint(b3b9f35e28a2282973cfae29ece66517482801391307c04b8b377b811f5ca696:1): chan_id=1406723972670423041, capacity=0.01 BTC
lnd: 2018-02-08 18:20:10.794 [INF] CRTR: New channel discovered! Link connects 03d34d5e5dc13248180e277bfa7787a383819cb223ff88e3d015ea6695e6ee026c and 03e45421ccecc831395ef2ba9eadc5ccde61332f055796cf6ba461aa617bba6aa3 with ChannelPoint(a2d4213edbbb4314e7726985ed8770b7374980e14197e29d5bbe9dc93eaec665:0): chan_id=1405754203414462464, capacity=0.005 BTC
lnd: 2018-02-08 18:20:11.765 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2018-02-08 18:20:11.766 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]
lnd: 2018-02-08 18:20:17.951 [INF] CRTR: New channel discovered! Link connects 039ae2ef0c151e1e9032521002893dee94a5751c827e4941b5167f9d655a997c6f and 03bd457958e7f21fcc928efcfdce00ef969404668b808aad32d40f1f8762f080d8 with ChannelPoint(8bbe6d2a9106898d14aadf105e13f43aea4f5fdbe94a41a9de88359db5e10763:0): chan_id=1402568918243278848, capacity=0.1 BTC
lnd: 2018-02-08 18:20:17.951 [INF] DISC: Broadcasting batch of 5 new announcements
lnd: 2018-02-08 18:20:18.498 [INF] CRTR: New channel discovered! Link connects 028a54250ed06f2522ae8690338c870251e4e88a9dcca81497ea71a5123eb66ef9 and 02b0627883f87f5d954c2ee217e51bf380745fe764b73d36150f0b80c32199ff27 with ChannelPoint(9a1e502d9fd1482252f1a353438f3697cc99e232e24920a460c85c801917792c:0): chan_id=1387384662655107072, capacity=0.01212121 BTC
lnd: 2018-02-08 18:20:18.586 [INF] CRTR: New channel discovered! Link connects 02250beb27a2535554ffededf3e25d39ed36900a6959be3d0b13aa0cd20a89fffc and 0373844c28a31de6266e07d582a39f822053860113b527389f5961259bb5893852 with ChannelPoint(8c05102b19ca412ef7e8452c2908d30d563ecdf1d7943b735cdc60957c703de0:0): chan_id=1386395102188077056, capacity=0.1 BTC
lnd: 2018-02-08 18:20:18.885 [INF] CRTR: New channel discovered! Link connects 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 and 03e687df4da3101e1989cde95a955360ff829f1b08222eff75620dc5aacd16acfa with ChannelPoint(73570825c5a85b37fb4f4984f91f210131e9924b97789c542c7a942ceeb0c586:0): chan_id=1385964093634052096, capacity=0.01 BTC
lnd: 2018-02-08 18:20:19.346 [INF] CRTR: New channel discovered! Link connects 0322cafa4fa838e6552162ce6a6369598d2933de348bedfb27854529461f9fa03f and 0372e8c16b4b3576dcc429d73418f48b33e59f04e77098673e2b040502ab307e37 with ChannelPoint(49434606e96348c3d6593aca162f15a21e268cc7a84e54fe0c49411b83190de8:0): chan_id=1385624344539693056, capacity=0.001 BTC
lnd: 2018-02-08 18:20:22.854 [INF] DISC: Obtained 4 addrs to bootstrap network with
lnd: 2018-02-08 18:20:23.231 [INF] SRVR: Established connection to: 18.218.207.229:9735
lnd: 2018-02-08 18:20:23.279 [ERR] SRVR: unable to connect to 0332845a98946a7fc4f0630b65743c4bfb2c4c02a3b3eb7d81886abda73491c7c5@162.225.190.212:9735: EOF
lnd: 2018-02-08 18:20:23.417 [INF] SRVR: Established connection to: 80.108.14.34:9737
lnd: 2018-02-08 18:20:23.483 [INF] DISC: Syncing channel graph state with 024213b8128786dec17187b8e1f74df34299c93c38a509e91f8c2c74f375e606a6, sending 0 vertexes and 9 edges 2018-02-08 18:20:23.483 [INF] SRVR: Attempting to send msgs 9 to: 024213b8128786dec17187b8e1f74df34299c93c38a509e91f8c2c74f375e606a6
lnd: 2018-02-08 18:20:23.674 [INF] SRVR: Established connection to: 128.199.234.109:9735
lnd: 2018-02-08 18:20:24.078 [INF] DISC: Syncing channel graph state with 03e9ada2d074edbcb2357104c8a6a530febfdc5adb2cf9dff822332ac8c7323935, sending 0 vertexes and 9 edges 2018-02-08 18:20:24.078 [INF] SRVR: Attempting to send msgs 9 to: 03e9ada2d074edbcb2357104c8a6a530febfdc5adb2cf9dff822332ac8c7323935
lnd: 2018-02-08 18:20:55.851 [INF] CRTR: New channel discovered! Link connects 02e6292da1ec2803f708688ba0317cb2c8c62767cf87bed6beaa0a0168499d6020 and 03e21c6c5faaa6467aa1c2703eed2756dbbdfe1056af05260a29cff63715c8b108 with ChannelPoint(542732e11f636551b438d109e8d7a801ae1f3dc016e2a982b62c4ccc286d14a3:0): chan_id=1385492403143245824, capacity=0.13655738 BTC 2018-02-08 18:20:55.851 [INF] DISC: Broadcasting batch of 5 new announcements
lnd: 2018-02-08 18:21:05.397 [INF] CRTR: New channel discovered! Link connects 03122f43c74f69017d73f45142874beba7e478535884ac215e1139ad3304c766e3 and 03b0f76fc1688915543308c0397e6b9b6d5636334760a5c34b2a73b8310dff29c8 with ChannelPoint(c75a29d561785a4bb5e36dbdb69588e187f337487d5fda60339f28c99cffa8b9:0): chan_id=1385728798138433536, capacity=0.025 BTC
lnd: 2018-02-08 18:21:45.199 [INF] CRTR: New channel discovered! Link connects 021fa3dd0026967a02b440b7454baa5f956f16414695ef532c0e503ee8b05739d1 and 028d741ad23cfb42971a9fe316588f84875f90cb1f2d9ec385b45e888ba5aa4b82 with ChannelPoint(c791a54f8f570b25911f749f9fceab97eefd01f16fc5c9f7e75c2598719533da:0): chan_id=1386669980093382656, capacity=0.1 BTC

</pre>
![lightning_v0_1_15_wallet_screen](https://user-images.githubusercontent.com/1884392/35985252-e41f54ee-0cfe-11e8-9134-e8e0afa93f05.png)

![lightning_v0_1_15_screen](https://user-images.githubusercontent.com/1884392/35985173-a8dba018-0cfe-11e8-97bc-51f8c79ac1f2.png)

**Comment by mntetai** [comment]
Possible solution should be a mandatory step of erasing all data.

**Comment by Roasbeef** [comment]
Is the public address not shown indefinitely? If the application has been offline for sometime, it may take a bit of time to resync its current state and ensure it has carried out all relevant on-chain actions (if required).

Note that you can also go directly to the receive tab to obtain a wallet address. Much of the rendering in the UI (atm) is deferred until `lnd` detects that it's "fully synced" to the chain. In your screenshot the blue section in the lower left corner is still glowing, meaning that `lnd` is still syncing with the chain.

**Comment by tcash1** [comment]
Etai - Did you get this resolved?   I'm getting the same on my Win10 machine

**Comment by tcash1** [comment]
lnd: 2018-02-27 05:42:13.699 [INF] SRVR: Initializing peer network boostrappers!
lnd: 2018-02-27 05:42:13.699 [INF] SRVR: Creating DNS peer boostrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory]]
lnd: 2018-02-27 05:42:13.699 [INF] CMGR: Server listening on [::]:9735 2018-02-27 05:42:13.699 [INF] ATPL: Instantiating autopilot with cfg: (*main.autoPilotConfig)(0xc0424ddb80)({ Active: (bool) true, MaxChannels: (int) 5, Allocation: (float64) 0.6 })
lnd: 2018-02-27 05:42:13.699 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph 2018-02-27 05:42:13.699 [INF] ATPL: Autopilot Agent starting
lnd: 2018-02-27 05:42:13.699 [INF] ATPL: Processing new external signal
lnd: 2018-02-27 05:42:13.775 [INF] DISC: Obtained 3 addrs to bootstrap network with
lnd: 2018-02-27 05:42:15.029 [ERR] SRVR: unable to connect to 020178567c0f881b579a7ddbcd8ce362a33ebba2b3c2d218e667f7e3b390e40d4e@45.32.138.203:9735: dial tcp 45.32.138.203:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:28.776 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2018-02-27 05:42:28.849 [INF] DISC: Obtained 6 addrs to bootstrap network with
lnd: 2018-02-27 05:42:29.133 [ERR] SRVR: unable to connect to 02622a58badb152d814885b09cff580a481f31f8e9a6cbe262dd5ea089331c49c3@37.235.49.48:9735: EOF
lnd: 2018-02-27 05:42:30.033 [ERR] SRVR: unable to connect to 02dc5e775414dd2167049200298632d5e2e68593f729298cf3945e60ab4d62fcc7@73.18.155.253:9735: dial tcp 73.18.155.253:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:30.108 [ERR] SRVR: unable to connect to 023dbcfb93a48cae101d0c5f782e25832d9b9dc06b119f4a1a2b9b2e101947248a@45.32.138.203:9735: dial tcp 45.32.138.203:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:30.112 [ERR] SRVR: unable to connect to 021954ba6575736c582a7785d1f5356714f7f2b47b7734e5ee20fee7bba780fbab@45.32.138.203:9735: dial tcp 45.32.138.203:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:34.777 [ERR] SRVR: unable to connect to 02eec2f92298fab9ed3a8f7f9f3519bcff9114a6061122c410a4bb78e279127a8a@54.144.74.89:9735: dial tcp 54.144.74.89:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:42:34.777 [ERR] SRVR: unable to connect to 02464bfaaae78b98268a6a6d7e8f6a110c60dd1293811d6029b11ee9edb4bbf869@87.157.126.83:9735: dial tcp 87.157.126.83:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
lnd: 2018-02-27 05:42:43.776 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2018-02-27 05:42:43.823 [INF] DISC: Obtained 7 addrs to bootstrap network with
lnd: 2018-02-27 05:42:44.963 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@24.12.185.155:9735: dial tcp 24.12.185.155:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:44.988 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@209.152.221.90:9735: dial tcp 209.152.221.90:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:49.851 [ERR] SRVR: unable to connect to 028c620eb95c3907a779adf9c47612973b70c322e5b60a21886947867439ff63e6@45.77.115.33:9735: dial tcp 45.77.115.33:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:42:49.851 [ERR] SRVR: unable to connect to 02b4f0aa3fd614644cbe75af230df222d9ec1270ad53ab5123bfec647140bb4708@45.77.115.33:9735: dial tcp 45.77.115.33:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
lnd: 2018-02-27 05:42:58.776 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2018-02-27 05:42:58.827 [INF] DISC: Obtained 6 addrs to bootstrap network with
lnd: 2018-02-27 05:42:59.964 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@24.12.185.155:9735: dial tcp 24.12.185.155:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:42:59.990 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@209.152.221.90:9735: dial tcp 209.152.221.90:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:43:00.088 [ERR] SRVR: unable to connect to 028ece9bb5b34c2e72acf9fec7403b201b13d2ddc66467e05c90609f24936de2cb@45.32.138.203:9735: dial tcp 45.32.138.203:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2018-02-27 05:43:04.826 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@38.124.71.15:9735: dial tcp 38.124.71.15:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:43:04.826 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@24.1.71.70:9735: dial tcp 24.1.71.70:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
lnd: 2018-02-27 05:43:04.826 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@128.111.13.23:9735: dial tcp 128.111.13.23:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:43:04.826 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@24.1.71.70:9735: dial tcp 24.1.71.70:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:43:04.826 [ERR] SRVR: unable to connect to 02c5953692050a69e29b7d4f2caddd8322a6f84667aea99461a63376341e4228e6@111.32.29.29:9735: dial tcp 111.32.29.29:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
lnd: 2018-02-27 05:43:16.256 [INF] BTCN: Processed 83 blocks in the last 1m51.32s (height 1286626, 2018-02-27 05:43:17 -0500 EST)
lnd: 2018-02-27 05:43:17.414 [INF] NTFN: New block: height=1286626, sha=00000000000012689d3b63dd3a29c8418dc7f7319b2ba2f773d75d4094e118eb
lnd: 2018-02-27 05:43:17.415 [INF] CRTR: Pruning channel graph using block 00000000000012689d3b63dd3a29c8418dc7f7319b2ba2f773d75d4094e118eb (height=1286626)
lnd: 2018-02-27 05:43:17.963 [INF] CRTR: Block 00000000000012689d3b63dd3a29c8418dc7f7319b2ba2f773d75d4094e118eb (height=1286626) closed 0 channels
lnd: 2018-02-27 05:43:19.829 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@111.32.29.29:9735: dial tcp 111.32.29.29:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:43:19.829 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@128.111.13.23:9735: dial tcp 128.111.13.23:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 2018-02-27 05:43:19.829 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@38.124.71.15:9735: dial tcp 38.124.71.15:9735: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
lnd: 2018-02-27 05:47:37.591 [INF] BTCN: Processed 1 block in the last 4m21.33s (height 1286627, 2018-02-27 05:47:37 -0500 EST)
lnd: 2018-02-27 05:47:38.576 [INF] NTFN: New block: height=1286627, sha=00000000000000e506a3568aacdfcc9493585e73b425ca40c72e50547657551d 2018-02-27 05:47:38.576 [INF] CRTR: Pruning channel graph using block 00000000000000e506a3568aacdfcc9493585e73b425ca40c72e50547657551d (height=1286627)
lnd: 2018-02-27 05:47:38.997 [INF] CRTR: Block 00000000000000e506a3568aacdfcc9493585e73b425ca40c72e50547657551d (height=1286627) closed 0 channels
lnd: 2018-02-27 05:50:52.803 [INF] BTCN: Processed 1 block in the last 3m15.21s (height 1286628, 2018-02-27 05:50:52 -0500 EST)
lnd: 2018-02-27 05:50:53.847 [INF] CRTR: Pruning channel graph using block 0000000000000144dd8a6d80cb7027431cf87f58763f0b32b6ea628992718268 (height=1286628) 2018-02-27 05:50:53.847 [INF] NTFN: New block: height=1286628, sha=0000000000000144dd8a6d80cb7027431cf87f58763f0b32b6ea628992718268
lnd: 2018-02-27 05:50:53.945 [INF] CRTR: Block 0000000000000144dd8a6d80cb7027431cf87f58763f0b32b6ea628992718268 (height=1286628) closed 0 channels
lnd: 2018-02-27 05:56:41.798 [INF] BTCN: Processed 1 block in the last 5m48.99s (height 1286629, 2018-02-27 05:56:42 -0500 EST)
lnd: 2018-02-27 05:56:42.726 [INF] NTFN: New block: height=1286629, sha=0000000000000062e0839fe4719a7e6545ae77aba317a778bad6d8995f6ab902
lnd: 2018-02-27 05:56:42.727 [INF] CRTR: Pruning channel graph using block 0000000000000062e0839fe4719a7e6545ae77aba317a778bad6d8995f6ab902 (height=1286629)
lnd: 2018-02-27 05:56:42.917 [INF] CRTR: Block 0000000000000062e0839fe4719a7e6545ae77aba317a778bad6d8995f6ab902 (height=1286629) closed 0 channels
lnd: 2018-02-27 06:01:12.102 [INF] BTCN: Processed 1 block in the last 4m30.3s (height 1286630, 2018-02-27 06:01:12 -0500 EST)
lnd: 2018-02-27 06:01:12.985 [INF] CRTR: Pruning channel graph using block 00000000000001e99fa9cfea9d3fb7b9356fc8767c48dc9d9dd37a9547ce963d (height=1286630) 2018-02-27 06:01:12.985 [INF] NTFN: New block: height=1286630, sha=00000000000001e99fa9cfea9d3fb7b9356fc8767c48dc9d9dd37a9547ce963d
lnd: 2018-02-27 06:01:13.066 [INF] CRTR: Block 00000000000001e99fa9cfea9d3fb7b9356fc8767c48dc9d9dd37a9547ce963d (height=1286630) closed 0 channels
lnd: 2018-02-27 06:21:20.949 [INF] BTCN: Processed 1 block in the last 20m8.84s (height 1286631, 2018-02-27 06:21:16 -0500 EST)
lnd: 2018-02-27 06:21:21.740 [INF] NTFN: New block: height=1286631, sha=000000000001bb7933803d4163e3d85b63d7812888f97cc8f2744905d433c0d6 2018-02-27 06:21:21.740 [INF] CRTR: Pruning channel graph using block 000000000001bb7933803d4163e3d85b63d7812888f97cc8f2744905d433c0d6 (height=1286631)
lnd: 2018-02-27 06:21:21.989 [INF] CRTR: Block 000000000001bb7933803d4163e3d85b63d7812888f97cc8f2744905d433c0d6 (height=1286631) closed 0 channels
lnd: 2018-02-27 06:22:09.766 [INF] BTCN: Processed 1 block in the last 48.81s (height 1286632, 2018-02-27 06:22:09 -0500 EST)
lnd: 2018-02-27 06:22:10.309 [INF] NTFN: New block: height=1286632, sha=00000000000000ea80ef868dd6fc18199f142674a0f5d58d535dbf2f7104fe50
lnd: 2018-02-27 06:22:10.309 [INF] CRTR: Pruning channel graph using block 00000000000000ea80ef868dd6fc18199f142674a0f5d58d535dbf2f7104fe50 (height=1286632)
lnd: 2018-02-27 06:22:10.409 [INF] CRTR: Block 00000000000000ea80ef868dd6fc18199f142674a0f5d58d535dbf2f7104fe50 (height=1286632) closed 0 channels
lnd: 2018-02-27 06:31:16.601 [INF] BTCN: Processed 1 block in the last 9m6.83s (height 1286633, 2018-02-27 06:31:16 -0500 EST)
lnd: 2018-02-27 06:31:17.179 [INF] NTFN: New block: height=1286633, sha=00000000000001950fa024aaab3f73c3f07350d900fbaa7737080ff78fad80fe
lnd: 2018-02-27 06:31:17.179 [INF] CRTR: Pruning channel graph using block 00000000000001950fa024aaab3f73c3f07350d900fbaa7737080ff78fad80fe (height=1286633)
lnd: 2018-02-27 06:31:17.279 [INF] CRTR: Block 00000000000001950fa024aaab3f73c3f07350d900fbaa7737080ff78fad80fe (height=1286633) closed 0 channels

**Comment by tcash1** [comment]
I've got ports 9735 & 10,009 open on my router & Windows FW's
