### ISSUE TITLE
Release v0.1.5-alpha on Mac not functional

### ISSUE THREAD

**Issue by pors** [lightninglabs/lightning-app#245]
### Description

Downloading and running the Mac binary results in a forever syncing app.

### Steps to reproduce the behavior

Download app here: https://github.com/lightninglabs/lightning-app/releases/download/v0.1.5-alpha/Lightning-darwin-x64v0.1.5.zip
Move app to /Applications folder
Run the app

### Expected behavior

After a while, the syncing should be finished

### Actual behavior

Syncing never finishes, may errors in the log

### Screenshot and/or logs if applicable

Logs here: https://files.slack.com/files-pri/T6AK88MGV-F9SKD5AS2/lightning-app_log.txt (requires access to the lightningcommunity slack.

**Comment by PJUllrich** [comment]
I don't have access to the logs, but I experience the same issue with the `0.2.0-prealpha` version. The logs indicate that the app has fully caught up with the chain (the latest block height in the logs is equal to the latest block height on e.g. Blockexplorer). However, I get the warning  
```
[info] /Applications/Lightning.app/Contents/Resources/assets/bin/darwin/lnd: 2018-07-05 11:44:36.791 [WRN] BTCN: Somehow we have 0 cfheaders for block 1 (00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206)
```
I think that this might be the problem. The chain is synced, but maybe not validated since the `cfheaders` for block 1 are missing?

**Comment by tanx** [comment]
@PJUllrich yes I created a new issue for prerelease. Closing in favor of https://github.com/lightninglabs/lightning-app/issues/433
