### ISSUE TITLE
Setup btcd 0.12.0 cluster on google cloud for testnet

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#383]

**Comment by Roasbeef** [comment]
To get around new nodes needing to sync the chain from scratch, we could add a mostly synced+indexed `btcd` chain in some storage bucket, and have the new nodes fetch that, then start up as normal. This way, new nodes would more or less achieve instant sync time. We'd need to then either manually sync the state every few days, or just set up some cron job to resync periodically.

**Comment by tanx** [comment]
> I set up autoscaling with a minimum of 1 node and maximum of 3. This has some potential for disruption since new nodes need to sync the chain from scratch

Or we could disable autoscaling and spin up node manually based on demand.

**Comment by tanx** [comment]
Autoscaling really only makes sense for stateless web services that persist to a database. In this case we should probably just keep a cluster of full nodes running and enable monitoring notify us when three nodes aren‘t enough.

**Comment by tanx** [comment]
Also I‘m wondering if the load balancer needs something like session stickyness or does the neutrino client just keep the tcp connection open indefinitely to a btcd node? If that‘s the case it might be worth checking if client connections are closed by the loadbalancer after a while.

**Comment by Roasbeef** [comment]
The neutrino protocol itself (unlike BIP 37) is stateless for both sides.
As a result, neutrino shouldn't have an issue if it connects to diff nodes
in the same cluster during its lifetime.

On Jun 15, 2018 4:05 AM, "Tankred Hase" <notifications@github.com> wrote:

Also I‘m wondering if the load balancer needs something like session
stickyness or does the neutrino client just keep the tcp connection open
indefinitely to a btcd node? If that‘s the case it might be worth checking
if client connections are closed by the loadbalancer after a while.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lightninglabs/lightning-app/issues/383#issuecomment-397588274>,
or mute the thread

**Comment by tanx** [comment]
> The neutrino protocol itself (unlike BIP 37) is stateless for both sides.
> As a result, neutrino shouldn't have an issue if it connects to diff nodes
> in the same cluster during its lifetime.

Ah ok interesting! Thanks

**Comment by valentinewallace** [comment]
> Autoscaling really only makes sense for stateless web servers that persist to a database on another host. In this case we should probably just keep a cluster of full nodes running and enable monitoring notify us when three nodes aren‘t enough.

Understood, turned off autoscaling. currently 2 replicas are running

**Comment by tanx** [comment]
Donzo :)
