### ISSUE TITLE
can not create channel

### ISSUE THREAD

**Issue by ac-com-au** [lightninglabs/lightning-app#43]
error: encoding/hex: odd length hex string

**Comment by DaReaper** [comment]
I used to get that error when the format of the channel's Public Key with the IP address is wrong. Publickey@ipaddress or Publickey@ipaddress:port was the correct format to be used. Check to see if the public key that you're pasting is of the correct length.

**Comment by ac-com-au** [comment]
2N9oz4fBot2z3rBkubRU25ZSY4ixfKTiyNm@46.101.133.194

**Comment by DaReaper** [comment]
@ac-com-au Are you sure "2N9oz4fBot2z3rBkubRU25ZSY4ixfKTiyNm" is a Public Key? It looks like a testnet wallet address to me.

**Comment by ac-com-au** [comment]
sorry that was my mistake but now with pub key different error
029f048c67944fca17e5b5d600890a1b186a779b1dd1c8a58450286746e1b93492@46.101.133.194
can not make connection to self

**Comment by DaReaper** [comment]
@ac-com-au When you're attempting to make a payment to another party, you need to connect to their channel. So you need to ask their publickey and their IP or you need to connect to a 3rd party channel to which both you and the 2nd party are connected to. Hence, you'll not be able to connect to yourself, since you're not going to make a payment to yourself. I hope this helps

**Comment by ac-com-au** [comment]
thank you for your time .
