### ISSUE TITLE
Pending channels should sort to the top of the channel list when they become open

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#610]
Currently, if pending channels at the bottom of the channel list become open, the list looks like:
```
[open channel]
[open channel]
[pending channel]
[pending channel]
[open channel]
[open channel]
```

Instead, channels that go from pending to open status should sort to the top when they become open.

**Comment by erkarl** [comment]
@valentinewallace could you provide steps on how to reproduce the issue? The logic for `computedChannels` sorting seems to work as intended.

I did, however, discover a similar issue where the channel status doesn't change when the application has been closed AND the channel status changes while the channels view is open. This is because after calling the `openChannel` or `closeChannel`  GRPC API we're attaching `stream.on('data', () => this.update());` listener (https://github.com/lightninglabs/lightning-app/blob/master/src/action/channel.js#L249 & https://github.com/lightninglabs/lightning-app/blob/master/src/action/channel.js#L286), but in a scenario where the application has been restarted the listener is no longer active.

Similarly, the `Can send` and `Can Receive` balances go out of sync when the remote node pays the invoice while the channels view is open.

**Comment by valentinewallace** [comment]
@erkarl I'm not sure what you mean when you say:
> the channel status doesn't change when the application has been closed AND the channel status changes while the channels view is open

I think this issue and/or karl's issue could be related to #657 and more generally not keeping the channels view up to date moment-to-moment. 

Perhaps similarly to how we poll for the wallet balance, we should poll `channel.update()`? We could only poll while the `Channels` view is open, so we're not polling too much all the time.

**Comment by erkarl** [comment]
> @erkarl I'm not sure what you mean when you say:
> 
> > the channel status doesn't change when the application has been closed AND the channel status changes while the channels view is open

If the application has been opened/closed there's no listener to trigger the `channel.update()` action. This is kind of an edge case because it assumes following conditions to be true:
1. user opens/closes channel(s)
2. user restarts the application
3. user navigates the channel view
4. the channel state changes
5. error - the updated channel(s') state is not reflected in the UI. The user has to navigate to home screen and back to trigger `channel.update()` 

> Perhaps similarly to how we poll for the wallet balance, we should poll `channel.update()`? We could only poll while the `Channels` view is open, so we're not polling too much all the time.

Perhaps we could wait for [new SubcribeChannel RPC for async notifications of channel state changes](https://github.com/lightningnetwork/lnd/issues/1235) to land in LND before moving forward with this issue?
