### ISSUE TITLE
Windows build is stuck at the welcome screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#631]

**Comment by erkarl** [comment]
Was able to replicate the issue on a fresh windows 10 installation (within a VM):
![screen shot 2018-09-07 at 13 29 42](https://user-images.githubusercontent.com/1056569/45214083-292c1100-b2a2-11e8-92c6-d23fef636860.png)

**Comment by tanx** [comment]
Ok thanks @erkarl. Can you paste the logs here? Does it also do this in dev mode?

**Comment by erkarl** [comment]
![screen shot 2018-09-07 at 15 00 05](https://user-images.githubusercontent.com/1056569/45218013-c9883280-b2ae-11e8-8eea-0e1cd7b78486.png)

@tanx turns out it's an easy fix. Looks like windows binary was built without the experimental flags turned on as per commit: `https://github.com/lightninglabs/lightning-app/commit/4140e5a7b9f27752937e8fe703a2c10996e1031e#diff-75787c1f3575f24b70d14aac4eaf85eb`

I managed to replicate the issue on OSX as well when I use LND without the experimental flags :).

**Comment by tanx** [comment]
> @tanx turns out it's an easy fix. Looks like windows binary was built without the experimental flags turned on as per commit: 4140e5a#diff-75787c1f3575f24b70d14aac4eaf85eb

Nice! Looks like we need to call the flags in `build_app.sh` as well...

**Comment by tanx** [comment]
See: https://github.com/lightninglabs/lightning-app/pull/633

**Comment by tanx** [comment]
Confirmed it worked for moli
