### ISSUE TITLE
Autofocus is broken starting on the 2nd page of seed restore

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#729]

**Comment by D4nte** [comment]
Indeed, need to hit `tab` 4 times to get the cursor in the first word field.

Also, when hitting `enter` it will go to the next page, even if a word is missing.

Hence, the user has to do
1. Enter 1st word
2. hit `tab`
3. Enter 2nd word
4. hit `tab`
5. Enter 3rd word
6. hit `enter`
7. hit `tab` four times
...

Would it be possible for `enter` to go to the next field instead of page?
Also, validation would be good as described in https://github.com/lightninglabs/lightning-app/issues/609

**Comment by tanx** [comment]
@bryanvu We already a PR in review for some time. It's unfortunately a hack and creates quite a bit of boiler plate code to work around considering the low prio of the issue. My hope is this will be fixed in a future version of `react-native-web`.

@valentinewallace did you open an issue in `react-native-web`?

**Comment by valentinewallace** [comment]
Closed by #1106.
