### ISSUE TITLE
Display a single unified balance on the home screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#920]
I've been thinking about our discussion regarding the home screen and the confusion and usability challenges we've seen around the balance numbers. None of the wording `Pending Deposit` or `Chain Deposit` has worked really well. My proposal is to display a single unified balance on the home screen that includes all on-chain as well as off-chain funds. To make sure users know if they can start doing lightning transactions, the balance should display a small indicator next to it that lights up when the app is ready to do lightning transactions.

My reasoning goes as follows:

1. In most cases it doesn't matter to the user how big the on-chain/off-chain balances are. Once there is a single open channel, the user can start spending.

2. Autopilot currently allocates 95% of funds to channels anyway. So the the unified number would be pretty close to the off-chain funds.

3. For the case that the user wants to transfer all funds out via a "wipe" on-chain transaction, we will provide them with a switch for autopilot in the settings.

What do you think @Roasbeef @bryanvu @valentinewallace ?

**Comment by bryanvu** [comment]
> the thing that is relevant is IF the user can do lightning transactions. Not how much. 
Not sure I understand/agree. If I want to send a payment, don't I want to know how much money I'm able to send? If I try to buy a $12 t-shirt, but I have $10 in channels and $10 on-chain, but I only see a single $20 balance, isn't that going to be confusing?

**Comment by bitcoinuser** [comment]
I don't understand why you don't choose to be a lightning only wallet. Things will be a lot easier to users. See the example of https://breez.technology/ wallet. They are a lightning wallet only and I think it's great.

Think about it. Thanks.

**Comment by bitcoinuser** [comment]
My idea is: use a hardware wallet to most of my funds. If I want to spend, I send only the necessary to a lightning wallet.

**Comment by tanx** [comment]
> I don't understand why you don't choose to be a lightning only wallet.

@bitcoinuser that's a good point and basically where our internal discussion ended up at. To recap:

1. Display a single unified balance on the homscreen
2. Display a small colored bar below  [----------|----|---] for *open/pending/on-chain* (@halseth )
3. Have autopilot allocate 95% of funds to channels (keep 5% on chain to close channels later)
4. Add feature to **disable autopilot and close all channels** in order to transfer funds out

I hope I didn't miss anything?

**Comment by valentinewallace** [comment]
@tanx FWIW I messaged the Breez wallet people asking how they handle this. They only show one balance.

**Comment by bitcoinuser** [comment]
@valentinewallace Yes, but they open the channel automatically to users (is non custodial), they don't let users open channels, and to remove funds I don't know how they give the option to users specify an amount. (I thought that if I only have one channel opened, I couldn't close it removing only part of the total amount)

![photo5100539329658333215](https://user-images.githubusercontent.com/1178856/52240338-b6a67800-28b7-11e9-947a-c8d665e25c34.jpg)

**Comment by valentinewallace** [comment]
@bitcoinuser I'm aware, but I still like their UX so I'd like to know their reasoning for choosing a single balance/what the balance represents (off vs on-chain, active vs. inactive).

**Comment by bitcoinuser** [comment]
@valentinewallace I like their UX too and I think Lightning App should go more and less the same way. 

Channel balance show the same amount from my breez home balance.

![photo5100535069050775635](https://user-images.githubusercontent.com/1178856/52241059-e6ef1600-28b9-11e9-88f0-d3057fe90253.jpg)

**Comment by valentinewallace** [comment]
@bitcoinuser oh cool. Lmk if you know if this number includes the following balances:
1. on-chain
2. pending-open channels
3. inactive channels
4. pending-closed channels

**Comment by molxyz** [comment]
@tanx @valentinewallace  Isn't Breeze a custodial wallet which totally has a different design and philosophy for their users?  It would be very confusing if lightning-app has only one balance for everything, that doesn't sound like what we want here. 

In order to open channels on lightning-app we have to send coins to the app wallet first before autopilot can open channels. It's not realistic to say let's make this app to be only for lightning and not onchain txs.  We need to have onchain txs to be in the app before channels can be opened, I'm not sure if @bitcoinuser understands this?  The lightning-app has the advantage of being a wallet for both on-chain and off-chain transactions, can be used in cases such as if a Lightning tx fails, we can use the same app to send the payment onchain. Lightning is still in very early days and txs on lightning do fail often.

In my opinion balances can be more clear on the home screen but one balance for everything is not realistic.  For lnd commandline we have `walletbalance` for onchain funds, `channelbalance` for total channel balance of the node owner. We could add `total balance` as the total of these two balance to let the owner of the app see what he/she has on the app. This is the design that Eclair mobile wallet has, and it looks very elegant and explanatory.

**Comment by tanx** [comment]
@tanx @valentinewallace Isn't Breeze a custodial wallet which totally has a different design and philosophy for their users?

@molxyz nope Breez is neutrino on Android.

> We need to have onchain txs to be in the app before channels can be opened

Yes obv. The question was more around how high autopilot allocation will be. It's 95% now and will likely stay that way. We decided to add an autopilot toggle feature in the settings so users can manage channels manually or do on-chain transactions to transfer funds out.

**Comment by tanx** [comment]
> In my opinion balances can be more clear on the home screen but one balance for everything is not realistic. For lnd commandline we have `walletbalance` for onchain funds, `channelbalance` for total channel balance of the node owner. We could add `total balance` as the total of these two balances to let the owner of the app see what he/she has on the app. This is the design that Eclair mobile wallet has, and it looks very elegant and explanatory.

We've gotten a lot of feedback around how multiple balances confuse user. We can disagree here, but I think a single balance is worth testing to see how it works with users.

**Comment by molxyz** [comment]
@tanx Hi, thanks for the quick reply.
If it's ok with you, let me explain how I've seen this since the beginning when I started testing this app. What I first saw was two numbers on the front home screen, one number bigger with no explanation or name to tell me what it was for, and the other number was "Pending Deposit" which made me think the deposit was perpetually in pending. Then later it was changed to "Chain Deposit" which made me think the deposit was on chain, kinda like "walletbalance", but i think for someone who just got to know about lightning it might not explain anything, or could be "my money deposit is somewhere else on some chain."  And I believe this is the confusion. 

For people who have been running LND, we are familiar with "walletbalance" and "channelbalance", and I've seen some people asking for "remotebalance" to be added. So to me "balance" numbers are not the issue, it's the wrong wording and lack of information/explanation are the issue.  I'm not sure why the app has a name for one number but no name for the other number?  Do you see what I'm saying about this inconsistency? 

Also, for most people using Lightning, they are very familiar with the Eclair mobile wallet app, and I haven't seen hardly anyone say they are confused about the balance numbers or design, except one person who said they wished there were arrows to tell them which direction, left or right, to swipe the screen (I've been reading their gitter quite often.) What's interesting to notice is they have icons for 'bitcoin' and 'lightning' like emojis next to these balance numbers, no words to explain but it seems that's how people understand it. Like emojis for their node aliases. Something in common that can click, no need for words? 

![image](https://user-images.githubusercontent.com/21127776/52254740-30049180-28dd-11e9-950a-f0dbf36a2418.png)

Sure, we can test a single balance, but which balance is it going to be? I can see more confusion, sorry to say that but this is how i feel!

**Comment by molxyz** [comment]
@tanx Okay, I'm willing to give it a try to test that too.  Maybe if we don't make the numbers so big like that's all there is on the home screen, that might be better?

**Comment by tanx** [comment]
> @tanx Okay, I'm willing to give it a try to test that too.

😮so releaved 🙂

> Maybe if we don't make the numbers so big like that's all there is on the home screen, that might be better?

Yeah we need to fix the font scaling especially for larger SAT numbers.
